import { Injectable } from '@angular/core';

const LANG = {
  "af":     {name: "Afrikaans", css:""},
  "af-ZA":  {name: "Afrikaans (South Africa)", css:""},
  "ar":     {name: "Arabic", css:""},
  "ar-AE":  {name: "Arabic (U.A.E.)", css:""},
  "ar-BH":  {name: "Arabic (Bahrain)", css:"bh"},
  "ar-DZ":  {name: "Arabic (Algeria)", css:"dz"},
  "ar-EG":  {name: "Arabic (Egypt)", css:"eg"},
  "ar-IQ":  {name: "Arabic (Iraq)", css:"iq"},
  "ar-JO":  {name: "Arabic (Jordan)", css:"jo"},
  "ar-KW":  {name: "Arabic (Kuwait)", css:"kw"},
  "ar-LB":  {name: "Arabic (Lebanon)", css:"lb"},
  "ar-LY":  {name: "Arabic (Libya)", css:"ly"},
  "ar-MA":  {name: "Arabic (Morocco)", css:"ma"},
  "ar-OM":  {name: "Arabic (Oman)", css:"om"},
  "ar-QA":  {name: "Arabic (Qatar)", css:"qa"},
  "ar-SA":  {name: "Arabic (Saudi Arabia)", css:"sa"},
  "ar-SY":  {name: "Arabic (Syria)", css:"sy"},
  "ar-TN":  {name: "Arabic (Tunisia)", css:"tn"},
  "ar-YE":  {name: "Arabic (Yemen)", css:"ye"},
  "az":     {name: "Azeri (Latin)", css:"az"},
  "az-AZ":  {name: "Azeri (Latin) (Azerbaijan)", css:"az"},
  // "az-AZ":  {name: "Azeri (Cyrillic) (Azerbaijan)", css:"az"},
  "be":     {name: "Belarusian", css:"by"},
  "be-BY":  {name: "Belarusian (Belarus)", css:"by"},
  "bg":     {name: "Bulgarian", css:"bg"},
  "bg-BG":  {name: "Bulgarian (Bulgaria)", css:"bg"},
  "bs-BA":  {name: "Bosnian (Bosnia and Herzegovina)", css:"ba"},
  "ca":     {name: "Catalan", css:""},
  "ca-ES":  {name: "Catalan (Spain)", css:"es"},
  "cs":     {name: "Czech", css:"cz"},
  "cs-CZ":  {name: "Czech (Czech Republic)", css:"cz"},
  "cy":     {name: "Welsh", css:""},
  "cy-GB":  {name: "Welsh (United Kingdom)", css:"gb"},
  "da":     {name: "Danish", css:""},
  "da-DK":  {name: "Danish (Denmark)", css:"dk"},
  "de":     {name: "German", css:"de"},
  "de-AT":  {name: "German (Austria)", css:"at"},
  "de-CH":  {name: "German (Switzerland)", css:"ch"},
  "de-DE":  {name: "German (Germany)", css:"de"},
  "de-LI":  {name: "German (Liechtenstein)", css:"li"},
  "de-LU":  {name: "German (Luxembourg)", css:"lu"},
  "dv":     {name: "Divehi", css:"md"},
  "dv-MV":  {name: "Divehi (Maldives)", css:"mv"},
  "el":     {name: "Greek", css:"gr"},
  "el-GR":  {name: "Greek (Greece)", css:"gr"},
  "en":     {name: "English", css:"gb"},
  "en-AU":  {name: "English (Australia)", css:"au"},
  "en-BZ":  {name: "English (Belize)", css:"bz"},
  "en-CA":  {name: "English (Canada)", css:"ca"},
  "en-CB":  {name: "English (Caribbean)", css:""},
  "en-GB":  {name: "English (United Kingdom)", css:"gb"},
  "en-IE":  {name: "English (Ireland)", css:"ie"},
  "en-JM":  {name: "English (Jamaica)", css:"jm"},
  "en-NZ":  {name: "English (New Zealand)", css:"nz"},
  "en-PH":  {name: "English (Republic of the Philippines)", css:"ph"},
  "en-TT":  {name: "English (Trinidad and Tobago)", css:"tt"},
  "en-US":  {name: "English (United States)", css:"us"},
  "en-ZA":  {name: "English (South Africa)", css:"za"},
  "en-ZW":  {name: "English (Zimbabwe)", css:"zw"},
  "eo":     {name: "Esperanto", css:""},
  "es":     {name: "Spanish", css:"es"},
  "es-AR":  {name: "Spanish (Argentina)", css:"ar"},
  "es-BO":  {name: "Spanish (Bolivia)", css:"bo"},
  "es-CL":  {name: "Spanish (Chile)", css:"cl"},
  "es-CO":  {name: "Spanish (Colombia)", css:"co"},
  "es-CR":  {name: "Spanish (Costa Rica)", css:"cr"},
  "es-DO":  {name: "Spanish (Dominican Republic)", css:"do"},
  "es-EC":  {name: "Spanish (Ecuador)", css:"ec"},
  // "es-ES":  {name: "Spanish (Castilian)", css:""},
  "es-ES":  {name: "Spanish (Spain)", css:"es"},
  "es-GT":  {name: "Spanish (Guatemala)", css:"gt"},
  "es-HN":  {name: "Spanish (Honduras)", css:"hn"},
  "es-MX":  {name: "Spanish (Mexico)", css:"mx"},
  "es-NI":  {name: "Spanish (Nicaragua)", css:"ni"},
  "es-PA":  {name: "Spanish (Panama)", css:"pa"},
  "es-PE":  {name: "Spanish (Peru)", css:"pe"},
  "es-PR":  {name: "Spanish (Puerto Rico)", css:"pr"},
  "es-PY":  {name: "Spanish (Paraguay)", css:"py"},
  "es-SV":  {name: "Spanish (El Salvador)", css:"sv"},
  "es-UY":  {name: "Spanish (Uruguay)", css:"uy"},
  "es-VE":  {name: "Spanish (Venezuela)", css:"ve"},
  "et":     {name: "Estonian", css:"ee"},
  "et-EE":  {name: "Estonian (Estonia)", css:"ee"},
  "eu":     {name: "Basque", css:""},
  "eu-ES":  {name: "Basque (Spain)", css:"es"},
  "fa":     {name: "Farsi", css:""},
  "fa-IR":  {name: "Farsi (Iran)", css:"ir"},
  "fi":     {name: "Finnish", css:""},
  "fi-FI":  {name: "Finnish (Finland)", css:"fi"},
  "fo":     {name: "Faroese", css:""},
  "fo-FO":  {name: "Faroese (Faroe Islands)", css:"fo"},
  "fr":     {name: "French", css:"fr"},
  "fr-BE":  {name: "French (Belgium)", css:"be"},
  "fr-CA":  {name: "French (Canada)", css:"ca"},
  "fr-CH":  {name: "French (Switzerland)", css:"ch"},
  "fr-FR":  {name: "French (France)", css:"fr"},
  "fr-LU":  {name: "French (Luxembourg)", css:"lu"},
  "fr-MC":  {name: "French (Principality of Monaco)", css:"mc"},
  "gl":     {name: "Galician", css:""},
  "gl-ES":  {name: "Galician (Spain)", css:"es"},
  "gu":     {name: "Gujarati", css:""},
  "gu-IN":  {name: "Gujarati (India)", css:"in"},
  "he":     {name: "Hebrew", css:""},
  "he-IL":  {name: "Hebrew (Israel)", css:"il"},
  "hi":     {name: "Hindi", css:""},
  "hi-IN":  {name: "Hindi (India)", css:"in"},
  "hr":     {name: "Croatian", css:""},
  "hr-BA":  {name: "Croatian (Bosnia and Herzegovina)", css:"ba"},
  "hr-HR":  {name: "Croatian (Croatia)", css:"hr"},
  "hu":     {name: "Hungarian", css:""},
  "hu-HU":  {name: "Hungarian (Hungary)", css:"hu"},
  "hy":     {name: "Armenian", css:""},
  "hy-AM":  {name: "Armenian (Armenia)", css:"am"},
  "id":     {name: "Indonesian", css:""},
  "id-ID":  {name: "Indonesian (Indonesia)", css:"id"},
  "is":     {name: "Icelandic", css:""},
  "is-IS":  {name: "Icelandic (Iceland)", css:"is"},
  "it":     {name: "Italian", css:"it"},
  "it-CH":  {name: "Italian (Switzerland)", css:"ch"},
  "it-IT":  {name: "Italian (Italy)", css:"it"},
  "ja":     {name: "Japanese", css:"jp"},
  "ja-JP":  {name: "Japanese (Japan)", css:"jp"},
  "ka":     {name: "Georgian", css:""},
  "ka-GE":  {name: "Georgian (Georgia)", css:"ge"},
  "kk":     {name: "Kazakh", css:""},
  "kk-KZ":  {name: "Kazakh (Kazakhstan)", css:"kz"},
  "kn":     {name: "Kannada", css:""},
  "kn-IN":  {name: "Kannada (India)", css:"in"},
  "ko":     {name: "Korean", css:""},
  "ko-KR":  {name: "Korean (Korea)", css:"kr"},
  "kok":    {name: "Konkani", css:""},
  "kok-IN": {name: "Konkani (India)", css:"in"},
  "ky":     {name: "Kyrgyz", css:""},
  "ky-KG":  {name: "Kyrgyz (Kyrgyzstan)", css:"kg"},
  "lt":     {name: "Lithuanian", css:""},
  "lt-LT":  {name: "Lithuanian (Lithuania)", css:"lt"},
  "lv":     {name: "Latvian", css:""},
  "lv-LV":  {name: "Latvian (Latvia)", css:"lv"},
  "mi":     {name: "Maori", css:""},
  "mi-NZ":  {name: "Maori (New Zealand)", css:"nz"},
  "mk":     {name: "FYRO Macedonian", css:""},
  "mk-MK":  {name: "FYRO Macedonian (Former Yugoslav Republic of Macedonia)", css:"mk"},
  "mn":     {name: "Mongolian", css:""},
  "mn-MN":  {name: "Mongolian (Mongolia)", css:"mn"},
  "mr":     {name: "Marathi", css:""},
  "mr-IN":  {name: "Marathi (India)", css:"in"},
  "ms":     {name: "Malay", css:""},
  "ms-BN":  {name: "Malay (Brunei Darussalam)", css:"bn"},
  "ms-MY":  {name: "Malay (Malaysia)", css:"my"},
  "mt":     {name: "Maltese", css:""},
  "mt-MT":  {name: "Maltese (Malta)", css:"mt"},
  "nb":     {name: "Norwegian (Bokm?l)", css:""},
  "nb-NO":  {name: "Norwegian (Bokm?l) (Norway)", css:"no"},
  "nl":     {name: "Dutch", css:""},
  "nl-BE":  {name: "Dutch (Belgium)", css:"be"},
  "nl-NL":  {name: "Dutch (Netherlands)", css:"nl"},
  "nn-NO":  {name: "Norwegian (Nynorsk) (Norway)", css:"no"},
  "ns":     {name: "Northern Sotho", css:""},
  "ns-ZA":  {name: "Northern Sotho (South Africa)", css:"za"},
  "pa":     {name: "Punjabi", css:""},
  "pa-IN":  {name: "Punjabi (India)", css:"in"},
  "pl":     {name: "Polish", css:"pl"},
  "pl-PL":  {name: "Polish (Poland)", css:"pl"},
  "ps":     {name: "Pashto", css:""},
  "ps-AR":  {name: "Pashto (Afghanistan)", css:"af"},
  "pt":     {name: "Portuguese", css:""},
  "pt-BR":  {name: "Portuguese (Brazil)", css:"br"},
  "pt-PT":  {name: "Portuguese (Portugal)", css:"pt"},
  "qu":     {name: "Quechua", css:""},
  "qu-BO":  {name: "Quechua (Bolivia)", css:"bo"},
  "qu-EC":  {name: "Quechua (Ecuador)", css:"ec"},
  "qu-PE":  {name: "Quechua (Peru)", css:"pe"},
  "ro":     {name: "Romanian", css:"ro"},
  "ro-RO":  {name: "Romanian (Romania)", css:"ro"},
  "ru":     {name: "Russian", css:"ru"},
  "ru-RU":  {name: "Russian (Russia)", css:"ru"},
  "sa":     {name: "Sanskrit", css:""},
  "sa-IN":  {name: "Sanskrit (India)", css:"in"},
  "se":     {name: "Sami (Northern)", css:""},
  "se-FI":  {name: "Sami (Northern) (Finland)", css:"fi"},
  // "se-FI":  {name: "Sami (Skolt) (Finland)", css:""},
  // "se-FI":  {name: "Sami (Inari) (Finland)", css:""},
  "se-NO":  {name: "Sami (Northern) (Norway)", css:"no"},
  // "se-NO":  {name: "Sami (Lule) (Norway)", css:""},
  // "se-NO":  {name: "Sami (Southern) (Norway)", css:""},
  "se-SE":  {name: "Sami (Northern) (Sweden)", css:"se"},
  // "se-SE":  {name: "Sami (Lule) (Sweden)", css:""},
  // "se-SE":  {name: "Sami (Southern) (Sweden)", css:""},
  "sk":     {name: "Slovak", css:"sk"},
  "sk-SK":  {name: "Slovak (Slovakia)", css:"sk"},
  "sl":     {name: "Slovenian", css:"si"},
  "sl-SI":  {name: "Slovenian (Slovenia)", css:"si"},
  "sq":     {name: "Albanian", css:"al"},
  "sq-AL":  {name: "Albanian (Albania)", css:"al"},
  "sr-BA":  {name: "Serbian (Latin) (Bosnia and Herzegovina)", css:"ba"},
  // "sr-BA":  {name: "Serbian (Cyrillic) (Bosnia and Herzegovina)", css:""},
  "sr-SP":  {name: "Serbian (Latin) (Serbia and Montenegro)", css:""},
  // "sr-SP":  {name: "Serbian (Cyrillic) (Serbia and Montenegro)", css:""},
  "sv":     {name: "Swedish", css:""},
  "sv-FI":  {name: "Swedish (Finland)", css:"fi"},
  "sv-SE":  {name: "Swedish (Sweden)", css:"se"},
  "sw":     {name: "Swahili", css:"ke"},
  "sw-KE":  {name: "Swahili (Kenya)", css:"ke"},
  "syr":    {name: "Syriac", css:"sy"},
  "syr-SY": {name: "Syriac (Syria)", css:"sy"},
  "ta":     {name: "Tamil", css:""},
  "ta-IN":  {name: "Tamil (India)", css:"in"},
  "te":     {name: "Telugu", css:""},
  "te-IN":  {name: "Telugu (India)", css:"in"},
  "th":     {name: "Thai", css:""},
  "th-TH":  {name: "Thai (Thailand)", css:"th"},
  "tl":     {name: "Tagalog", css:""},
  "tl-PH":  {name: "Tagalog (Philippines)", css:"ph"},
  "tn":     {name: "Tswana", css:""},
  "tn-ZA":  {name: "Tswana (South Africa)", css:"za"},
  "tr":     {name: "Turkish", css:""},
  "tr-TR":  {name: "Turkish (Turkey)", css:"tr"},
  "tt":     {name: "Tatar", css:""},
  "tt-RU":  {name: "Tatar (Russia)", css:"ru"},
  "ts":     {name: "Tsonga", css:""},
  "uk":     {name: "Ukrainian", css:""},
  "uk-UA":  {name: "Ukrainian (Ukraine)", css:"ua"},
  "ur":     {name: "Urdu", css:""},
  "ur-PK":  {name: "Urdu (Islamic Republic of Pakistan)", css:"pk"},
  "uz":     {name: "Uzbek (Latin)", css:""},
  "uz-UZ":  {name: "Uzbek (Latin) (Uzbekistan)", css:"uz"},
  // "uz-UZ":  {name: "Uzbek (Cyrillic) (Uzbekistan)", css:""},
  "vi":     {name: "Vietnamese", css:""},
  "vi-VN":  {name: "Vietnamese (Viet Nam)", css:"vn"},
  "xh":     {name: "Xhosa", css:""},
  "xh-ZA":  {name: "Xhosa (South Africa)", css:"za"},
  "zh":     {name: "Chinese", css:"cn"},
  "zh-CN":  {name: "Chinese (S)", css:"cn"},
  "zh-HK":  {name: "Chinese (Hong Kong)", css:"hk"},
  "zh-MO":  {name: "Chinese (Macau)", css:"mo"},
  "zh-SG":  {name: "Chinese (Singapore)", css:"sg"},
  "zh-TW":  {name: "Chinese (Taiwan)", css:"tw"},
  "zu":     {name: "Zulu", css:""},
  "zu-ZA":  {name: "Zulu (South Africa)", css:"za"},
};

@Injectable()
export class FlagService {
  private static getCountry(countryCode: string): any {
    let allLanguages = Object.keys(LANG);

    if (allLanguages.indexOf(countryCode) >= 0) {
      if (LANG[countryCode].css.length > 0) {
        // if found, return details of the country
        return LANG[countryCode];
      } else if (countryCode.indexOf('-') >= 0 && LANG[countryCode.split('-').shift()].css.length > 0) {
        // if country does not have a valid css property, we try to use its parent ("en" is the parent of "en-US")
        return LANG[countryCode.split('-').shift()];
      } else {
        return null;
      }
    } else {
      return null;
    }
  }

  // public methods

  public static getCountriesList(): any[] {
    let list = [];

    for(let code in LANG) {
      let country = LANG[code];
      list.push({
        languageName: country.name,
        languageCode: code,
        flagClass: country.css
      });
    }

    return list;
  }

  public static getClassName(countryCode: string): string {
    let contryDetails = FlagService.getCountry(countryCode);
    let prefix = 'flag-icon-';

    return (contryDetails !== null) ? prefix + contryDetails.css : '';
  }

  public static getLanguageName(countryCode: string): string {
    let contryDetails = FlagService.getCountry(countryCode);

    return (contryDetails !== null) ? contryDetails.name : '';
  }
}